import { config as envConfig } from "dotenv"
envConfig({ path: "./.env.development" })

export const config = {
  NODE_ENV: process.env.NODE_ENV,
  APP_NAME: process.env.APP_NAME,
  AUTH_DATABASE_URI: process.env.AUTH_DATABASE_URI,
  PLATFORM_DATABASE_URI: process.env.PLATFORM_DATABASE_URI,
  APPS_DATABASE_URI: process.env.APPS_DATABASE_URI,
  REDIS_URI: process.env.REDIS_URI,
  AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY,
  AZURE_OPENAI_DEPLOYMENT_URI: process.env.AZURE_OPENAI_DEPLOYMENT_URI,
  NEWS_API_URI: process.env.NEWS_API_URI,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  OTP_HASHING_KEY: process.env.OTP_HASHING_KEY,
  JWT_SECRET_ACCESS_TOKEN: process.env.JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN: process.env.JWT_SECRET_REFRESH_TOKEN,
  SUBSCRIPTION_PRICE: process.env.SUBSCRIPTION_PRICE,
  GCP_MAILER_REDIRECT_URI: process.env.GCP_MAILER_REDIRECT_URI,
  GCP_MAILER_CLIENT_ID: process.env.GCP_MAILER_CLIENT_ID,
  GCP_MAILER_CLIENT_SECRET: process.env.GCP_MAILER_CLIENT_SECRET,
  GCP_MAILER_REFRESH_TOKEN: process.env.GCP_MAILER_REFRESH_TOKEN,
  GCP_MAILER_FROM_EMAIL: process.env.GCP_MAILER_FROM_EMAIL,
  GOOGLE_OAUTH_VERIFICATION_API: process.env.GOOGLE_OAUTH_VERIFICATION_API,
  AZURE_OPENAI_BASE_MODEL: process.env.AZURE_OPENAI_BASE_MODEL,
  UI_URL: process.env.UI_URL,
  API_URL: process.env.API_URL,
}
