export enum EventMap {
  SendEmail = "sendEmail",
  CreateAnalytics = "createAnalytics",
  GetAnalyticsTrend = "getAnalyticsTrend",
  GetUserDetails = "getUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  ActivateTrial = "activateTrial",
  GetTotalWealth = "getTotalWealth",
  GetTotalDebt = "getTotalDebt",
  CreateSpace = "createSpace",
  GetSpaceList = "getSpaceList",
  GetAssetList = "getAssetList",
  GetDebtList = "getDebtList",
  GetGoalList = "getGoalList",
  GetNearestGoal = "getNearestGoal",
  CreateDebt = "createDebt",
  CreateGoal = "createGoal",
  GetExpenseByMonth = "getExpenseByMonth",
  CreateExpense = "createExpense",
}
