export enum EventMap {
  SetToken = "setToken",
  GetToken = "getToken",
  DeleteToken = "deleteToken",
  SendEmail = "sendEmail",
  CreateActivity = "createActivity",
  GetUserDetails = "getUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  ActivateInitialFreeSubscription = "activateInitialFreeSubscription",
  GetTotalWealth = "getTotalWealth",
  FindPortfolioByName = "findPortfolioByName",
  CreatePortfolio = "createPortfolio",
  GetPortfolioList = "getPortfolioList",
  UpdateAttribute = "updateAttribute",
}
