export enum EventsUnion {
  SetToken = "setToken",
  GetToken = "getToken",
  DeleteToken = "deleteToken",
  SendEmail = "sendEmail",
  CreateActivity = "createActivity",
  GetUserDetails = "getUserDetails",
  UpdateUserDetails = "updateUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  GetAPIKeyDetails = "getAPIKeyDetails",
  GetBaseModelDetails = "getBaseModelDetails",
  GetThreadCount = "getThreadCount",
  CreateAPIKey = "createAPIKey",
  GetAPIKeys = "getAPIKeys",
}
