export enum EventMap {
  GetRefreshToken = "getRefreshToken",
  SendEmail = "sendEmail",
  CreateActivity = "createActivity",
  GetUserDetails = "getUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  ActivateTrial = "activateTrial",
  GetTotalWealth = "getTotalWealth",
  GetTotalDebt = "getTotalDebt",
  FindInstitutionByName = "findInstitutionByName",
  CreateInstitution = "createInstitution",
  GetInstitutionList = "getInstitutionList",
  GetAssetList = "getAssetList",
  UpdateAttribute = "updateAttribute",
  GetInstitutionDetailsById = "getInstitutionDetailsById",
  GetAssetDetailsById = "getAssetDetailsById",
  GetDebtDetailsById = "getDebtDetailsById",
  GetGoalDetailsById = "getGoalDetailsById",
}
