export enum EventMap {
  GetRefreshToken = "getRefreshToken",
  SendEmail = "sendEmail",
  CreateAnalytics = "createAnalytics",
  GetAnalyticsTrend = "getAnalyticsTrend",
  GetUserDetails = "getUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  ActivateTrial = "activateTrial",
  GetTotalWealth = "getTotalWealth",
  GetTotalDebt = "getTotalDebt",
  CreateSpace = "createSpace",
  GetSpaceList = "getSpaceList",
  GetAssetList = "getAssetList",
  UpdateAttribute = "updateAttribute",
  GetSpaceDetailsById = "getSpaceDetailsById",
  GetAssetDetailsById = "getAssetDetailsById",
  GetDebtDetailsById = "getDebtDetailsById",
  GetGoalDetailsById = "getGoalDetailsById",
  GetDebtList = "getDebtList",
  GetGoalList = "getGoalList",
  GetNearestGoal = "getNearestGoal",
  CreateDebt = "createDebt",
  CreateGoal = "createGoal",
}
