export enum EventMap {
  GetRefreshToken = "getRefreshToken",
  SendEmail = "sendEmail",
  CreateAnalytics = "createAnalytics",
  GetUserDetails = "getUserDetails",
  GetSubscriptionDetails = "getSubscriptionDetails",
  ActivateTrial = "activateTrial",
  GetTotalWealth = "getTotalWealth",
  GetTotalDebt = "getTotalDebt",
  FindInstitutionByName = "findInstitutionByName",
  CreateInstitution = "createInstitution",
  GetInstitutionList = "getInstitutionList",
  GetAssetList = "getAssetList",
  UpdateAttribute = "updateAttribute",
  GetInstitutionDetailsById = "getInstitutionDetailsById",
  GetAssetDetailsById = "getAssetDetailsById",
  GetDebtDetailsById = "getDebtDetailsById",
  GetGoalDetailsById = "getGoalDetailsById",
  GetDebtList = "getDebtList",
  GetGoalList = "getGoalList",
  GetNearestGoal = "getNearestGoal",
  CreateDebt = "createDebt",
  CreateGoal = "createGoal",
}
