export enum InstitutionType {
  BANK = "BANK",
  GOVERNMENT = "GOVERNMENT",
  OTHER = "OTHER",
}

export enum AssetType {
  LUMPSUM_DEPOSIT = "LUMPSUM_DEPOSIT",
  RECURRING_DEPOSIT = "RECURRING_DEPOSIT",
  METAL = "METAL",
  REAL_ESTATE = "REAL_ESTATE",
  BOND = "BOND",
  LIQUID = "LIQUID",
  RETIREMENT = "RETIREMENT",
  EQUITY = "EQUITY",
  CRYPTO = "CRYPTO",
  OTHER = "OTHER",
}

export enum RecurringFrequency {
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  HALF_YEARLY = "HALF_YEARLY",
  YEARLY = "YEARLY",
}
